### ISSUE TITLE
Results' ranking by the closest location

### ISSUE THREAD

**Issue by RucajDenisa** [CityZenApp/Android-Development#19]
Would be good to rank the results starting by the closest one to the current mobile location. 
I think this will save lots of time for the user and is useful.

**Comment by rskikuli** [comment]
Many thanks, @RucajDenisa. This is tricky since will require us to host the ratings on our server and also might create legal issues in some cases, due to the fact that some business owners might think that we are responsible for a bad review they might get. Other than this is a very nice proposal and I already added this to the wiki page with the other proposals. You can find it [here](https://github.com/CityZenApp/CityZen-Android/wiki/Ideas-&-proposals).

**Comment by jbelien** [comment]
@rskikuli I do think "user rating" is involved in the proposition of @RucajDenisa ; if I understand correctly she just wants to see the results sorted by distance between the POI and the current location.

Could be already the case though ; but if it's not, it would be nice indeed :)

**Comment by rskikuli** [comment]
@jbelien @RucajDenisa oh I totally misread that. IIt is a really good idea and relatively easily implemented. I'm adding both ideas on the proposed features.
