### ISSUE TITLE
Only finding POIs mapped as nodes

### ISSUE THREAD

**Issue by trigpoint** [CityZenApp/Android-Development#41]
When searching only results for POIs mapped as node are found. Those mapped as ways are ignored.

**Comment by rskikuli** [comment]
Thank you for filing this bug @trigpoint. Can you please share more info so that we investigate further? What are you

- harware (phone/tablet model);
- Android version;
- location (or at least country of continent where you tried this);
- maybe some screenshot?  

If you don't feel comfortable sharing these info we totally understand. In the mean time labeling this as a big. Thanks.

**Comment by jbelien** [comment]
I think it's a duplicate of #24 !

**Comment by rskikuli** [comment]
Closing this as it is a duplicate of #24 . Thank for your contribution.
