### ISSUE TITLE
Searching in map does not work

### ISSUE THREAD

**Issue by mikemaikaefer** [CityZenApp/Android-Development#90]
Hi,

when I open CityZen, select the "Map"-symbol on lower end of screen, then press the "Search"-button (the magnifier-glass) and type something I want to find, it does not work. After starting the search nothing happens, even when I search for very common cities or nearby places.

So for me it seems, this function is completely broken (using version 1.0 from F-Droid with Android 6.0).

**Comment by rskikuli** [comment]
Thank you for initiating this @mikemaikaefer . We have done a lot of improvements in the new 1.1 version including better a fully functional search option (thank you @AndyScherzinger). We are working with F-droid to launch the new version asap. You can follow the updates about this issue here  #57. Would be thankfu if you could also try the new version and send us your feedback.

**Comment by AndyScherzinger** [comment]
@rskikuli this bug exists (now) and I already have a fix (PR coming very soon). This would also be happening with the actual master (HTTP301 - moved permanently). Will be fixed with the next release :+1:

**Comment by AndyScherzinger** [comment]
Fixing PR is #92
